"""Validate the committed ct_town_crosswalk.csv against its invariants.

build_ct_crosswalk.py asserts these when the crosswalk is regenerated by hand,
but nothing checked the committed artifact itself until now. Everything CT
joins through this file, so a bad edit or regeneration must not merge.
"""
from pathlib import Path
import pandas as pd
import pytest

CROSSWALK = (
    Path(__file__).resolve().parents[1] / "reference" / "ct_crosswalk" / "ct_town_crosswalk.csv"
)

LEGACY_COUNTIES = {"09001", "09003", "09005", "09007", "09009", "09011", "09013", "09015"}
PLANNING_REGIONS = {"09110", "09120", "09130", "09140", "09150", "09160", "09170", "09180", "09190"}


@pytest.fixture(scope="module")
def crosswalk():
    return pd.read_csv(CROSSWALK, dtype=str)


def test_169_towns_8_counties_9_regions(crosswalk):
    assert len(crosswalk) == 169
    assert crosswalk["county_fips"].nunique() == 8
    assert crosswalk["region_fips"].nunique() == 9


def test_county_codes_are_the_legacy_set(crosswalk):
    assert set(crosswalk["county_fips"]) == LEGACY_COUNTIES


def test_region_codes_are_the_planning_region_set(crosswalk):
    assert set(crosswalk["region_fips"]) == PLANNING_REGIONS


def test_fips_are_zero_padded_digit_strings(crosswalk):
    for col, width in [("town_fips_2020", 10), ("town_fips_2022", 10),
                       ("county_fips", 5), ("region_fips", 5)]:
        assert (crosswalk[col].str.len() == width).all(), f"{col} not all {width} chars"
        assert crosswalk[col].str.isdigit().all(), f"{col} has non-digit characters"


def test_county_fips_matches_town_2020_prefix(crosswalk):
    assert (crosswalk["county_fips"] == crosswalk["town_fips_2020"].str[:5]).all()


def test_no_missing_names(crosswalk):
    for col in ("town_name", "county_name", "region_name"):
        assert crosswalk[col].notna().all(), f"missing values in {col}"


def test_no_duplicate_towns(crosswalk):
    assert not crosswalk["town_fips_2020"].duplicated().any()
    assert not crosswalk["town_fips_2022"].duplicated().any()
